name: Rust Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Discover tasks
        id: discover
        run: |
          # collecting folders with task names
          tasks=$(find . -maxdepth 1 -type d ! -name .)
          echo "tasks=${tasks}" >> $GITHUB_ENV

      - name: Run tests for each task
        run: |
          # Przechodzenie przez każdy folder i uruchamianie testów
          for task in ${{ steps.discover.outputs.tasks }}; do
            echo "Running tests in $task"
            cd "$task"
            cargo test
            cd ..
          done
