name: Rust Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1
        with:
          rust-version: stable

      - name: Run tests for each task
        run: |
          tasks=(
            acronym
            beer-song
            collatz-conjecture
            etl
            hamming
            kindergarten-garden
            matching-brackets
            pangram
            proverb
            series
            all-your-base
            binary-search
            difference-of-squares
            gigasecond
            hello-world
            leap
            minesweeper
            parallel-letter-frequency
            raindrops
            space-age
            anagram
            bob
            diffie-hellman
            grade-school
            high-scores
            luhn
            nth-prime
            poker
            README.md
            sublist
            armstrong-numbers
            clock
            eliuds-eggs
            grains
            isogram
            macros
            nucleotide-count
            prime-factors
            reverse-string
            sum-of-multiples
          )

          for task in "${tasks[@]}"; do
            echo "Running tests in $task"
            cd "$task"
            cargo test || exit 1  # Stop if any test fails
            cd ..
          done
